declare module '@sotaproject/strikethrough' {}
declare module '@editorjs/underline' {}
declare module '@editorjs/header' {}
declare module '@editorjs/embed' {}
declare module '@editorjs/table' {}
declare module '@editorjs/list' {}
declare module '@editorjs/code' {}
declare module '@editorjs/link' {}
declare module '@editorjs/inline-code' {}
